name: C++17 Clang Build with Google Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2：安装必要的依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang-14 g++-14 libgtest-dev

      # 步骤 3：创建构建目录
      - name: Create build directory
        run: mkdir build

      # 步骤 4：配置 CMake
      - name: Configure CMake
        working-directory: build
        run: |
          cmake -GNinja \
                -DCMAKE_CXX_COMPILER=clang++-14 \
                -DCMAKE_CXX_STANDARD=17 \
                ..

      # 步骤 5：编译项目
      - name: Build project
        working-directory: build
        run: ninja

      # 步骤 6：运行单元测试
      - name: Run tests anyTests
        working-directory: build
        run: ./tests/anyTests

      - name: Run tests LRUTests
        working-directory: build
        run: ./tests/LRUTests

      - name: Run tests SkipListTests
        working-directory: build
        run: ./tests/SkipListTests

      - name: Run tests callbackTests
        working-directory: build
        run: ./tests/callbackTests

      - name: Run tests queueTests
        working-directory: build
        run: ./tests/queueTests

      - name: Run tests runTests
        working-directory: build
        run: ./tests/runTests

      - name: Run tests tupleTests
        working-directory: build
        run: ./tests/tupleTests

      - name: Run tests configTests
        working-directory: build
        run: ./tests/configTests

      - name: Run tests optionalTests
        working-directory: build
        run: ./tests/optionalTests

      - name: Run tests alloctorTests
        working-directory: build
        run: ./tests/alloctorTests
